# Collection Namespace
namespace: kube_cloud

# Collection Name
name: haproxy

# Collection Version
version: 2.0.1

# Collection README (Summary)
readme: README.md

# Collection Authors
authors:
- KubeCloud (github.com/kube-cloud)
- Jean-Jacques ETUNE NGI <jetune@kube-cloud.com>


# Vollection Description
description: KubeCloud Ansible HA Proxy Collection

# Collection License (https://spdx.org/licenses/) : (Mutualy exclusive with 'license_file' property)
license:
- Apache-2.0

# License File (Mutualy exclusive with 'license' property)
# license_file: LICENCE

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags:
- system
- proxy
- lb
- linux

# Collection Dependencies
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies: {
  "community.general": ">=4.0.0"
}

# The URL of the originating SCM repository
repository: https://github.com/kube-cloud/ansible-collection-haproxy

# The URL to any online docs
documentation: https://github.com/kube-cloud/ansible-collection-haproxy/tree/main/docs

# The URL to the homepage of the collection/project
homepage: https://github.com/kube-cloud/ansible-collection-haproxy

# The URL to the collection issue tracker
issues: https://github.com/kube-cloud/ansible-collection-haproxy/issues

build_ignore:
  - ".editorconfig"
  - ".gitignore"
